"use client";
import Link from "next/link";
import { Bot, CirclePlay, MoreHorizontal, Plus, Search } from "lucide-react";
import { useMemo, useState } from "react";

export type AutomationListItem = { id: string; nome: string; descricao: string; gatilho: string; status: string; conversas: number; contatos: number; atualizadaEm: string };
export function AutomacoesList({ automacoes }: { automacoes: AutomationListItem[] }) { const [query, setQuery] = useState(""); const filtered = useMemo(() => { const term = query.trim().toLocaleLowerCase("pt-BR"); return term ? automacoes.filter((item) => [item.nome, item.descricao, item.gatilho, item.status].some((value) => value.toLocaleLowerCase("pt-BR").includes(term))) : automacoes; }, [automacoes, query]); return <section className="mt-8 overflow-hidden rounded-2xl border border-[#dfede3] bg-[#fbfefc] shadow-[0_1px_2px_rgba(23,32,51,0.03)]"><div className="flex flex-col gap-4 border-b border-[#e5efe8] p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold text-[#172033]">Todas as automações</h2><p className="mt-1 text-sm text-[#8a91a2]">Gerencie os fluxos conectados ao seu WhatsApp.</p></div><div className="relative w-full sm:w-[280px]"><Search className="absolute left-3 top-1/2 size-[17px] -translate-y-1/2 text-[#9ba2b1]" /><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar automação..." className="h-10 w-full rounded-xl border border-[#dce8df] bg-white pl-10 pr-4 text-sm text-[#172033] outline-none transition placeholder:text-[#a4aab7] focus:border-[#79a789] focus:ring-4 focus:ring-[#dcefe2]/60" /></div></div>{automacoes.length === 0 ? <EmptyState /> : filtered.length > 0 ? <div className="divide-y divide-[#e8f0ea]">{filtered.map((automacao) => <AutomationRow key={automacao.id} automacao={automacao} />)}</div> : <div className="flex min-h-48 items-center justify-center p-5 text-center text-sm text-[#858c9c]">Nenhuma automação encontrada.</div>}</section>; }
function AutomationRow({ automacao }: { automacao: AutomationListItem }) { return <div className="group flex flex-col gap-5 p-5 transition hover:bg-[#f8fcf9] lg:flex-row lg:items-center"><div className="flex min-w-0 flex-1 items-start gap-4"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-[#e2f2e7] text-[#286342]"><Bot className="size-5" /></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate font-semibold text-[#172033]">{automacao.nome}</h3><StatusBadge status={automacao.status} /></div><p className="mt-1 max-w-xl truncate text-sm text-[#858c9c]">{automacao.descricao}</p><div className="mt-3 flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-[#848b9b]"><span className="inline-flex items-center gap-1.5"><CirclePlay className="size-3.5" />Gatilho:<strong className="font-semibold text-[#596173]">{automacao.gatilho}</strong></span><span>Atualizada <strong className="font-medium text-[#596173]">{automacao.atualizadaEm}</strong></span></div></div></div><div className="flex items-center gap-8 border-t border-[#edf2ee] pt-4 lg:border-0 lg:pt-0"><Metric value={automacao.conversas} label="Conversas" /><Metric value={automacao.contatos} label="Contatos" /></div><div className="flex items-center gap-2"><Link href={`/dashboard/automacoes/${automacao.id}`} className="inline-flex h-10 flex-1 items-center justify-center rounded-xl border border-[#d7e6dc] bg-white px-5 text-sm font-semibold text-[#35694a] transition hover:border-[#bcd5c5] hover:bg-[#edf7f0] lg:flex-none">Editar</Link><button type="button" className="flex size-10 items-center justify-center rounded-xl text-[#858c9c] transition hover:bg-[#edf7f0] hover:text-[#286342]" aria-label="Mais opções"><MoreHorizontal className="size-5" /></button></div></div>; }
function Metric({ value, label }: { value: number; label: string }) { return <div><p className="text-lg font-bold text-[#172033]">{value}</p><p className="text-xs text-[#9298a6]">{label}</p></div>; }
function StatusBadge({ status }: { status: string }) { if (status === "ativa") return <span className="inline-flex items-center gap-1.5 rounded-full bg-[#e3f4e8] px-2.5 py-1 text-[11px] font-semibold text-[#2d7046]"><span className="size-1.5 rounded-full bg-[#3a9b5c]" />Ativa</span>; if (status === "pausada") return <span className="inline-flex items-center gap-1.5 rounded-full bg-[#fff2d9] px-2.5 py-1 text-[11px] font-semibold text-[#9a681f]"><span className="size-1.5 rounded-full bg-[#d79b3b]" />Pausada</span>; return <span className="inline-flex items-center gap-1.5 rounded-full bg-[#f0f1f4] px-2.5 py-1 text-[11px] font-semibold text-[#737a89]"><span className="size-1.5 rounded-full bg-[#9ba1ad]" />Rascunho</span>; }
function EmptyState() { return <div className="flex min-h-[350px] flex-col items-center justify-center px-5 py-12 text-center"><div className="flex size-14 items-center justify-center rounded-2xl bg-[#e2f2e7] text-[#286342]"><Bot className="size-6" /></div><h3 className="mt-5 font-semibold text-[#172033]">Nenhuma automação criada</h3><p className="mt-2 max-w-sm text-sm leading-6 text-[#858c9c]">Crie sua primeira automação para começar a atender seus clientes automaticamente pelo WhatsApp.</p><Link href="/dashboard/automacoes/nova" className="mt-5 inline-flex h-10 items-center gap-2 rounded-xl bg-[#286342] px-4 text-sm font-semibold text-white transition hover:bg-[#205638]"><Plus className="size-4" />Criar automação</Link></div>; }
